# Generated by Django 2.0.3 on 2018-03-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="link",
            field=models.URLField(
                error_messages={"unique": "This link already exists!"},
                unique=True,
                verbose_name="link",
            ),
        )
    ]
