# Generated by Django 2.0.5 on 2018-05-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180401_0016'),
    ]

    operations = [
        migrations.RenameField('Posts', 'link', 'url'),
    ]
